language: scala
scala:
- 2.10.1
jdk:
- oraclejdk7
- openjdk7
deploy:
  provider: heroku
  api_key:
    secure: DL0YopU/ahty8Jw1b243q6AIFuIAPcseOx5OoP3FrjM7htfiWr1MrL0dyulgkfJhw7L1HMeUB3GUWwIezafZiJIiub45gaWue7JlIxxFOM4RTjpYo+5BMEdphtu3+GhHBRazo3udUteMQ2sMsPZSIPFvKLOsppu8g3JR99Cp5+A=
  app: Chess
  on:
    repo: Synesso/forkpin
