language: scala
scala:
- 2.10.1
jdk:
- oraclejdk7
- openjdk7
deploy:
  provider: heroku
  api_key:
    secure: S/K2e16/qBjSUCmuX18zA8OeC3VECX22IRcrybZrxMDkFb6m/OQ/s3wyVc0iDSwMsMT1AlH0unPbAjA3WmKf4eG0pi5H9YdVcHjTepejUba0B2tpvJ5OD6weyp4Iaq2M2vepW2yRt/XUNmf4LSd9lV5f96HutvlmSDGpdykNoJ4=
  app: sheltered-brushlands-1468
  on:
    repo: Synesso/forkpin
    jdk: oraclejdk7
